CREATE DATABASE IF NOT EXISTS KIOSKO;

USE KIOSKO;

CREATE TABLE IF NOT EXISTS USUARIO(ID_USER INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,USER VARCHAR(9),PASS VARCHAR(15),ESPACIO INTEGER,EMAIL VARCHAR(40),DIRECTORIO VARCHAR(35));
