CREATE DATABASE IF NOT EXISTS KIOSKO;

USE KIOSKO;

CREATE TABLE IF NOT EXISTS USUARIO(ID_USER INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,USER VARCHAR(9),PASS VARCHAR(15),ESPACIO INTEGER);


CREATE TABLE IF NOT EXISTS DOCUMENTO(ID_DOCUMENTOS INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,USER_D INTEGER,FOREIGN KEY(USER_D) REFERENCES USUARIO(ID_USER),NOMBRE_D VARCHAR(20),EXTENCION VARCHAR(20),TAMANO INTEGER,RUTA VARCHAR(40));


INSERT INTO USUARIO VALUES(NULL,415112132,"ADMIN");
INSERT INTO DOCUMENTO VALUES(NULL,1,"TEST","TEST",1023,"TEST");